<?php

namespace App\Console\Commands;

use App\Models\Template;
use Illuminate\Console\Command;

class DeleteHiddenTemplate extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:template:delete';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Delete hidden template, generated by automatically!';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        Template::where('hidden', true)->where('removable', false)->withoutGlobalScope('hidden')->delete();
        return 0;
    }
}

